# Generated by Django 4.0.4 on 2024-09-09 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
    ]
